export const activePath = {
  "/ozfund/work-mange":["/ozfund/work-mange"],
  "/ozfund/work-mange/todo":["/ozfund/work-mange","/ozfund/work-mange/todo"],
  "/ozfund/work-mange/mange-site": ["/ozfund/work-mange","/ozfund/work-mange/mange-site"],
  "/ozfund/work-mange/business-mange": ["/ozfund/work-mange","/ozfund/work-mange/business-mange"],
  "/ozfund/work-mange/toto-contract": ["/ozfund/work-mange","/ozfund/work-mange/toto-contract"],
  "/ozfund/work-mange/ozc-contract": ["/ozfund/work-mange","/ozfund/work-mange/ozc-contract"],
  "/ozfund/website-operation": ["/ozfund/website-operation"],
  "/ozfund/website-operation/zh-cn": ["/ozfund/website-operation","/ozfund/website-operation/zh-cn"],
  "/ozfund/website-operation/zh-wt": ["/ozfund/website-operation","/ozfund/website-operation/zh-wt"],
  "/ozfund/website-operation/en": ["/ozfund/website-operation","/ozfund/website-operation/en"],
  "/ozfund/website-operation/japan": ["/ozfund/website-operation","/ozfund/website-operation/japan"],
  "/ozfund/email": ["/ozfund/email"],
  "/ozfund/email/list": ["/ozfund/email","/ozfund/email/list"],
  "/ozfund/email/temp": ["/ozfund/email","/ozfund/email/temp"],
  "/ozfund/email/send": ["/ozfund/email","/ozfund/email/send"],
  "/ozfund/email/record": ["/ozfund/email","/ozfund/email/record"],
  "/ozfund/assets": ["/ozfund/assets"],
  "/ozfund/assets/toto": ["/ozfund/assets","/ozfund/assets/toto"],
  "/ozfund/assets/ozc": ["/ozfund/assets","/ozfund/assets/ozc"],
  "/ozfund/assets/toto-price": ["/ozfund/assets","/ozfund/assets/toto-price"],
  "/ozfund/assets/toto_ozc": ["/ozfund/assets","/ozfund/assets/toto_ozc"],
  "/ozfund/permission": ["/ozfund/permission"],
  "/ozfund/permission/staff-list": ["/ozfund/permission","/ozfund/permission/staff-list"],
  "/ozfund/IP": ["/ozfund/IP"],
  "/ozfund/IP/list": ["/ozfund/IP","/ozfund/IP/list"],
  "/ozfund/IP/change-record": ["/ozfund/IP","/ozfund/IP/change-record"],
  "/ozfund/logs": ["/ozfund/logs"],
  "/ozfund/logs/sign": ["/ozfund/logs","/ozfund/logs/sign"],
  "/ozfund/logs/operation": ["/ozfund/logs","/ozfund/logs/operation"],
  "/ozfund/logs/work": ["/ozfund/logs","/ozfund/logs/work"],
  "/ozfund/business": ["/ozfund/business"],
  "/ozfund/personal": ["/ozfund/personal"],
  
};
export const activePathToName = {
  
};
