function activeAddr(type, name = '') {
  const commonPath = `/ozfund/website-operation`
  const childRoute = ['process', 'trends', 'notice', 'problem']
  const childRouteName = ['进程', '动态', '公告', '常见问题']
  const pathList = {}
  const nameList = {}
  for (let index = 0; index < childRoute.length; index++) {
    const item = childRoute[index];
    let key = `${commonPath}/${type}/${item}`
    pathList[key] = [`${commonPath}`, `${commonPath}/${type}`, `${key}`]
    nameList[key] = ["Ozfund网站运营", name, childRouteName[index]]
  }
  return { pathList, nameList }
}
export const activePath = {
  "/ozfund/work-mange": ["/ozfund/work-mange"],
  "/ozfund/work-mange/todo": ["/ozfund/work-mange", "/ozfund/work-mange/todo"],
  "/ozfund/work-mange/mange-site": ["/ozfund/work-mange", "/ozfund/work-mange/mange-site"],
  "/ozfund/work-mange/business-mange": ["/ozfund/work-mange", "/ozfund/work-mange/business-mange"],
  "/ozfund/work-mange/business-mange/aridrop-address": ["/ozfund/work-mange", "/ozfund/work-mange/business-mange", "/ozfund/work-mange/business-mange/aridrop-address"],
  "/ozfund/work-mange/business-mange/batch-transfer": ["/ozfund/work-mange", "/ozfund/work-mange/business-mange", "/ozfund/work-mange/business-mange/batch-transfer"],
  "/ozfund/work-mange/business-mange/draws-contract": ["/ozfund/work-mange", "/ozfund/work-mange/business-mange", "/ozfund/work-mange/business-mange/draws-contract"],
  "/ozfund/work-mange/business-mange/release-custody": ["/ozfund/work-mange", "/ozfund/work-mange/business-mange", "/ozfund/work-mange/business-mange/release-custody"],
  "/ozfund/work-mange/toto-contract": ["/ozfund/work-mange", "/ozfund/work-mange/toto-contract"],
  "/ozfund/work-mange/ozc-contract": ["/ozfund/work-mange", "/ozfund/work-mange/ozc-contract"],
  "/ozfund/work-mange/ozc-contract/publish-ozc": ["/ozfund/work-mange", "/ozfund/work-mange/ozc-contract", "/ozfund/work-mange/ozc-contract/publish-ozc"],
  "/ozfund/work-mange/ozc-contract/frezz-address": ["/ozfund/work-mange", "/ozfund/work-mange/ozc-contract", "/ozfund/work-mange/ozc-contract/frezz-address"],
  "/ozfund/work-mange/ozc-contract/destroy-address": ["/ozfund/work-mange", "/ozfund/work-mange/ozc-contract", "/ozfund/work-mange/ozc-contract/destroy-address"],
  "/ozfund/work-mange/ozc-contract/add-delete": ["/ozfund/work-mange", "/ozfund/work-mange/ozc-contract", "/ozfund/work-mange/ozc-contract/add-delete"],
  "/ozfund/website-operation": ["/ozfund/website-operation"],
  "/ozfund/website-operation/zh-cn": ["/ozfund/website-operation", "/ozfund/website-operation/zh-cn"],
  ...activeAddr('zh-cn').pathList,
  "/ozfund/website-operation/zh-wt": ["/ozfund/website-operation", "/ozfund/website-operation/zh-wt"],
  "/ozfund/website-operation/en": ["/ozfund/website-operation", "/ozfund/website-operation/en"],
  "/ozfund/website-operation/japan": ["/ozfund/website-operation", "/ozfund/website-operation/japan"],
  "/ozfund/email": ["/ozfund/email"],
  "/ozfund/email/list": ["/ozfund/email", "/ozfund/email/list"],
  "/ozfund/email/temp": ["/ozfund/email", "/ozfund/email/temp"],
  "/ozfund/email/send": ["/ozfund/email", "/ozfund/email/send"],
  "/ozfund/email/record": ["/ozfund/email", "/ozfund/email/record"],
  "/ozfund/assets": ["/ozfund/assets"],
  "/ozfund/assets/toto": ["/ozfund/assets", "/ozfund/assets/toto"],
  "/ozfund/assets/toto/allocation-statistics": ["/ozfund/assets", "/ozfund/assets/toto", "/ozfund/assets/toto/allocation-statistics"],
  "/ozfund/assets/toto/assets-statistics": ["/ozfund/assets", "/ozfund/assets/toto", "/ozfund/assets/toto/assets-statistics"],
  "/ozfund/assets/ozc": ["/ozfund/assets", "/ozfund/assets/ozc"],
  "/ozfund/assets/toto-price": ["/ozfund/assets", "/ozfund/assets/toto-price"],
  "/ozfund/assets/toto_ozc": ["/ozfund/assets", "/ozfund/assets/toto_ozc"],
  "/ozfund/permission": ["/ozfund/permission"],
  "/ozfund/permission/staff-list": ["/ozfund/permission", "/ozfund/permission/staff-list"],
  "/ozfund/IP": ["/ozfund/IP"],
  "/ozfund/IP/list": ["/ozfund/IP", "/ozfund/IP/list"],
  "/ozfund/IP/change-record": ["/ozfund/IP", "/ozfund/IP/change-record"],
  "/ozfund/logs": ["/ozfund/logs"],
  "/ozfund/logs/sign": ["/ozfund/logs", "/ozfund/logs/sign"],
  "/ozfund/logs/operation": ["/ozfund/logs", "/ozfund/logs/operation"],
  "/ozfund/logs/work": ["/ozfund/logs", "/ozfund/logs/work"],
  "/ozfund/business": ["/ozfund/business"],
  "/ozfund/personal": ["/ozfund/personal"],
};
export const activePathToName = {
  "/ozfund/work-mange": ["Ozfund事务管理"],
  "/ozfund/work-mange/todo": ["Ozfund事务管理", "待办事务"],
  "/ozfund/work-mange/mange-site": ["Ozfund事务管理", "管理员设置"],
  "/ozfund/work-mange/business-mange": ["Ozfund事务管理", "TOTO业务管理"],
  "/ozfund/work-mange/toto-contract": ["Ozfund事务管理", "TOTO合约设置"],
  "/ozfund/work-mange/ozc-contract": ["Ozfund事务管理", "OZC合约设置"],
  "/ozfund/work-mange/ozc-contract/publish-ozc": ["Ozfund事务管理", "OZC合约设置", "增发OZC"],
  "/ozfund/work-mange/ozc-contract/frezz-address": ["Ozfund事务管理", "OZC合约设置", "冻结地址"],
  "/ozfund/work-mange/ozc-contract/destroy-address": ["Ozfund事务管理", "OZC合约设置", "销毁地址"],
  "/ozfund/work-mange/ozc-contract/add-delete": ["Ozfund事务管理", "OZC合约设置", "可兑换代币新增与移除"],
  "/ozfund/website-operation": ["Ozfund网站运营"],
  "/ozfund/website-operation/zh-cn": ["Ozfund网站运营", "简体中文"],
  ...activeAddr('zh-cn', '简体中文').nameList,
  "/ozfund/website-operation/zh-wt": ["Ozfund网站运营", "繁体中文"],
  "/ozfund/website-operation/en": ["Ozfund网站运营", "English"],
  "/ozfund/website-operation/japan": ["Ozfund网站运营", "しろうと"],
  "/ozfund/email": ["Ozfund订阅邮箱"],
  "/ozfund/email/list": ["Ozfund订阅邮箱", "邮箱列表"],
  "/ozfund/email/temp": ["Ozfund订阅邮箱", "邮箱模板"],
  "/ozfund/email/send": ["Ozfund订阅邮箱", "邮件定时发送"],
  "/ozfund/email/record": ["Ozfund订阅邮箱", "邮件发送记录"],
  "/ozfund/assets": ["资产统计"],
  "/ozfund/assets/toto": ["资产统计", "TOTO"],
  "/ozfund/assets/toto/assets-statistics": ["资产统计", "TOTO", "TOTO资产统计"],
  "/ozfund/assets/toto/allocation-statistics": ["资产统计", "TOTO", "TOTO分配统计"],
  "/ozfund/assets/ozc": ["资产统计", "OZC资产统计"],
  "/ozfund/assets/toto-price": ["资产统计", "TOTO兑换价格核算"],
  "/ozfund/assets/toto_ozc": ["资产统计", "TOTO/OZC价格统计"],
  "/ozfund/permission": ["权限管理"],
  "/ozfund/permission/staff-list": ["权限管理", "员工列表"],
  "/ozfund/IP": ["IP管理"],
  "/ozfund/IP/list": ["IP管理", "IP列表"],
  "/ozfund/IP/change-record": ["IP管理", "IP变动记录"],
  "/ozfund/logs": ["日志管理"],
  "/ozfund/logs/sign": ["日志管理", "登录日志"],
  "/ozfund/logs/operation": ["日志管理", "操作日志"],
  "/ozfund/logs/work": ["日志管理", "事务日志"],
  "/ozfund/business": ["业务管理"],
  "/ozfund/personal": ["个人资料"],
};
