export const activePath = {
  "/aupay/data": ["/aupay/data"],
  "/aupay/assets": ["/aupay/assets"],
  "/aupay/user":["/aupay/user"],
  "/aupay/user/detail/user": ["/aupay/user","/aupay/user/detail/user"],
  "/aupay/user/detail/assetsChanges": ["/aupay/user","/aupay/user/detail/assetsChanges"],
  "/aupay/user/detail/trade": ["/aupay/user","/aupay/user/detail/trade"],
  "/aupay/user/detail/draw": ["/aupay/user","/aupay/user/detail/draw"],
  "/aupay/user/detail/recharge": ["/aupay/user","/aupay/user/detail/recharge"],
  "/aupay/address/user": ["/aupay/address", "/aupay/address/user"],
  "/aupay/address/transfer": ["/aupay/address", "/aupay/address/transfer"],
  "/aupay/address/reserve": ["/aupay/address", "/aupay/address/reserve"],
  "/aupay/address/draw": ["/aupay/address", "/aupay/address/draw"],
  "/aupay/address/minerFees": ["/aupay/address", "/aupay/address/minerFees"],
  "/aupay/ozbet": ["/aupay/ozbet"],
  "/aupay/ozbet/assets": ["/aupay/ozbet", "/aupay/ozbet/assets"],
  "/aupay/ozbet/draw": ["/aupay/ozbet", "/aupay/ozbet/draw"],
  "/aupay/ozbet/assets/transfer-records": [
    "/aupay/ozbet",
    "/aupay/ozbet/assets",
  ],
  "/aupay/personal": ["/aupay/personal"],
  "/aupay/system/staff-manage": [
    "/aupay/system",
    "/aupay/system/staff-manage",
  ],
  "/aupay/system/logs-manage": ["/aupay/system", "/aupay/system/logs-manage"],
  "/aupay/system/rate-manage": ["/aupay/system", "/aupay/system/rate-manage"],
  "/aupay/system/draw": ["/aupay/system", "/aupay/system/draw"],
  "/aupay/system/automated": ["/aupay/system", "/aupay/system/automated"],
  "/aupay/system/ip-record": ["/aupay/system", "/aupay/system/ip-record"],
  "/aupay/system/ip-manage": ["/aupay/system", "/aupay/system/ip-manage"],
  "/aupay/notice": ["/aupay/notice"],
  "/aupay/notice/add": ["/aupay/notice","/aupay/notice/add"],
  "/aupay/system/staff-manage/detail": ["/aupay/system/staff-manage","/aupay/system/staff-manage/detail"],
};
export const activePathToName = {
  "/aupay/data": ["数据统计"],
  "/aupay/assets": ["资产统计"],
  "/aupay/user": ["用户管理"],
  "/aupay/user/detail/user": ["用户管理", "用户详情"],
  "/aupay/user/detail/assetsChanges": ["用户管理", "资产变动记录"],
  "/aupay/user/detail/trade": ["用户管理", "交易记录"],
  "/aupay/user/detail/draw": ["用户管理", "提币记录"],
  "/aupay/user/detail/recharge": ["用户管理", "充币记录"],
  "/aupay/address/user": ['地址管理',"用户地址"],
  "/aupay/address/transfer": ['地址管理',"中转地址"],
  "/aupay/address/reserve": ['地址管理',"储备资产"],
  "/aupay/address/draw": ['地址管理',"提币地址"],
  "/aupay/address/minerFees": ['地址管理',"矿工费地址"],
  "/aupay/ozbet/assets": ['Ozbet',"Ozbet资产地址"],
  "/aupay/ozbet/draw": ['Ozbet',"Ozbet提款地址"],
  "/aupay/ozbet/assets/transfer-records": ["Ozbet提款地址", "转账记录"],
  "/aupay/personal": ["个人资料"],
  "/aupay/system/staff-manage": ["系统管理","员工管理"],
  "/aupay/system/logs-manage": ["系统管理","日志记录"],
  "/aupay/system/rate-manage": ["系统管理","汇率管理"],
  "/aupay/system/draw": ["系统管理","提币设置"],
  "/aupay/system/automated": ["系统管理","自动化配置"],
  "/aupay/system/ip-record": ["系统管理","IP记录"],
  "/aupay/system/ip-manage": ["系统管理","IP管理"],
  "/aupay/system/staff-manage/detail": ["系统管理","员工管理", "详情"],
  "/aupay/notice": ["公告列表"],
  "/aupay/notice/add": ["公告列表", "新增公告"],
};
